// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Shadow DB is used only by `prisma migrate dev/diff` to replay migrations
    // and detect drift. Harmless when unset for normal runs; set
    // SHADOW_DATABASE_URL when authoring migrations.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
